### ISSUE TITLE
Include in the main Kodi repository?

### ISSUE THREAD

**Issue by mintsoft** [TheAssassin/kodi-invidious-plugin#10] opened 2022-01-22 12:35 UTC
Hiya,

Trying to get an updated version of YTChannels into the main Kodi repo which has the option to use invidious (https://github.com/xbmc/repo-plugins/pull/3847#issuecomment-1019113987) . They've expressed concern that this addon isn't in their repo and therefore we can't depend on it as they can't "see" the behaviour changes over time (which seems like a perfectly valid reason to me).

Is there any reason why this addon isn't in the main Kodi repo (I appreciate it's a bit of messing around etc)?

Thanks,
Rob

**Comment by DJCrashdummy** [comment] 2022-03-15 07:09
it would be awesome to create at least a kodi-addon-repo (like it is done at https://github.com/lekma/plugin.video.invidious), so also noobs can install this addon and receive updates easily.

*BTW: why there are a few Invidious-addons? please don't tell me the reason are the different licenses (like in my mentioned example GPL3 & MIT) and that is why we are splitting forces.*

**Comment by mintsoft** [comment] 2022-03-17 21:23
@DJCrashdummy I don't think there's any particular licensing restriction here; it all looks compatible to me. I'd happily do the work to put it _into_ the main repository as I'm already set-up for it, however I don't want to just do that and look like I'm sort of "stealing" it or whatever

**Comment by TheAssassin** [comment] 2022-03-17 21:25
Just go ahead. The code is published under the MIT license at the moment, please don't hesitate to contact me in case this is an issue.

The main reason this repository sees little activity is a lack of time, also I hardly use Kodi at the moment for playing YouTube stuff.

**Comment by mintsoft** [comment] 2022-03-19 09:48
@TheAssassin Cool, I'll fork this and get it packaged up. I'll PR in any changes that are necessary to get it into the main repo? I don't think there'll be much, however it seems like the addon.xml might need a few tweaks

**Comment by TheAssassin** [comment] 2022-03-23 01:44
Please feel free to contribute any changes back to this repository. I can invite you as a collaborator, too, if you want to (as long as you won't break anything).

**Comment by DJCrashdummy** [comment] 2022-09-15 14:25
it has finally landed there: https://kodi.tv/addons/matrix/plugin.video.invidious
but well... unfortunately it seems pretty outdated. :frowning_face:

**Comment by mintsoft** [comment] 2022-09-16 19:41
@DJCrashdummy the version number is basically invented for the purposes of getting it into the repo. Is there something specific missing?

**Comment by DJCrashdummy** [comment] 2022-10-12 16:07
@mintsoft well... the issue is not about what's missing, but about the addon not working at all. :frowning_face: 

i described my situation at an other issue #18 (because i thought the 2 invidious addons are closely related), but still the issue with this addon - installed from the official repo - still persists (https://github.com/TheAssassin/kodi-invidious-plugin/issues/18#issuecomment-1249725301):
> i'm using the latest OSMC (2022.03-1) which uses Kodi 19.4 and is based on Debian 10 Buster. the addon from the official repo (0.1.0+matrix.1) can be installed, but if i try to send any request to the chosen invidious instance - no mater which one - i get a **403 response**.

**Comment by mintsoft** [comment] 2022-10-12 17:29
@DJCrashdummy I'll update the version in the main repo; that's not difficult, however I'm not convinced it will necessarily fix the problem as I can't see a fix for the issue inside the addon itself?

Just to clarify, the version in the main kodi repo is this one: https://github.com/TheAssassin/kodi-invidious-plugin if there are other forks that have additional functionality/fixes etc then that's not going to be resolved by me updating the main repo

**Comment by DJCrashdummy** [comment] 2022-10-13 18:03
yes, as already clarified with @TheAssassin at #18, i'm aware that there are 2 different addons... and as described there: i tried this addon - installed from the official repo - unsuccessfully before even thinking about installing the other addon.

i have no idea what causes the 403... but it happened on 2 different devices. :shrug:

**Comment by TheAssassin** [comment] 2022-12-26 19:26
Closing as resolved.

**Closed as completed by TheAssassin** 2022-12-26 19:26 UTC
